# Generated by Django 2.0.5 on 2024-05-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_user_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
