# Generated by Django 2.0.5 on 2020-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200613_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cell_number',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
