# Generated by Django 2.0.5 on 2020-08-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_user_cell_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
