# Generated by Django 2.0.5 on 2024-09-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_user_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='person_eyes_color',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='person_height',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='primary_id_src',
            new_name='personal_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_id_type',
        ),
    ]
