# Generated by Django 2.0.5 on 2020-08-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200810_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
