# Generated by Django 2.0.5 on 2020-08-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200810_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
