# Generated by Django 2.0.5 on 2020-09-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
