# Generated by Django 2.0.5 on 2021-03-02 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20210227_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSTCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.TextField()),
                ('card_type', models.TextField()),
                ('qr_code', models.TextField()),
                ('renew_status', models.TextField()),
                ('issued', models.DateTimeField(auto_now_add=True)),
                ('expired', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='person_eyes_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='person_height',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_id_src',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='primary_id_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sstcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sst_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
