# Generated by Django 2.0.5 on 2021-03-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20210303_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sstcard',
            name='card_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sstcard',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sstcard',
            name='renew_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
