# Generated by Django 2.0.5 on 2021-05-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20210303_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
