# Generated by Django 2.0.5 on 2022-12-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('app_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_courses', to='courses.Course'),
        ),
        migrations.AddField(
            model_name='packagecourse',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app_cart.Package'),
        ),
        migrations.AddField(
            model_name='package',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='courses.Subject'),
        ),
    ]
