# Generated by Django 2.0.5 on 2021-09-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0002_auto_20210925_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='qty',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Approved'), (1, 'Rejected')], default=0),
        ),
    ]
