# Generated by Django 2.0.5 on 2023-10-11 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20231009_0246'),
        ('app_cart', '0003_auto_20231002_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_item', to='courses.Enrollments'),
        ),
    ]
