# Generated by Django 2.0.5 on 2021-10-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20210921_1259'),
        ('app_cart', '0004_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_courses', to='courses.Course')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app_cart.Package')),
            ],
            options={
                'ordering': ['package'],
            },
        ),
    ]
