# Generated by Django 2.0.5 on 2023-10-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0004_item_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Rejected')], default=0),
        ),
    ]
