# Generated by Django 2.0.5 on 2024-12-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0005_auto_20231020_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='free_credits',
            field=models.IntegerField(default=0),
        ),
    ]
