# Generated by Django 2.0.5 on 2022-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20220429_1555'),
        ('app_cart', '0005_packagecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='subjects',
            field=models.ManyToManyField(to='courses.Subject'),
        ),
    ]
