# Generated by Django 2.0.5 on 2022-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0006_package_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='courses.Subject'),
        ),
    ]
