# Generated by Django 2.0.5 on 2024-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0006_package_free_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Courses Bundle'), (2, 'Subject Linked'), (3, 'Free Credits')], default=0),
        ),
    ]
