# Generated by Django 2.0.5 on 2024-12-18 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_cart', '0007_package_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUserCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_purchased', models.IntegerField(default=0)),
                ('credits_remaining', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'is_business': True}, on_delete=django.db.models.deletion.CASCADE, related_name='business_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business User Credit',
                'verbose_name_plural': 'Business User Credits',
            },
        ),
    ]
