# Generated by Django 2.0.5 on 2024-12-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0008_businessusercredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessusercredit',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='credits', to='app_cart.Order'),
        ),
    ]
