# Generated by Django 2.0.5 on 2024-09-20 06:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_business', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessStudents',
            new_name='CompanyStudents',
        ),
    ]
