# Generated by Django 2.0.5 on 2024-09-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_business', '0002_auto_20240920_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companystudents',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='companystudents',
            old_name='student_id',
            new_name='student',
        ),
    ]
