# Generated by Django 2.0.5 on 2024-09-20 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_business', '0003_auto_20240920_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyStudents',
            new_name='BusinessEmployee',
        ),
    ]
