# Generated by Django 2.0.5 on 2024-10-23 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursefeature_header'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_business', '0004_auto_20240920_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_history', models.TextField(blank=True, null=True)),
                ('is_assigned', models.BooleanField(default=0)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_business_courses', to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_course_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
