# Generated by Django 2.0.5 on 2020-03-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('courses', '0002_auto_20200320_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_quiz', to='students.Quiz'),
        ),
    ]
