# Generated by Django 2.0.5 on 2020-03-18 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200318_0930'),
        ('courses', '0003_cluster_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quiz', to='students.Quiz'),
        ),
    ]
