# Generated by Django 2.0.5 on 2023-10-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_studentcertificate_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcertificate',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.Enrollments'),
        ),
    ]
