# Generated by Django 2.0.5 on 2020-04-07 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_module_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_progress', to='courses.Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
