# Generated by Django 2.0.5 on 2023-10-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20231009_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='user_ip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
