# Generated by Django 2.0.5 on 2024-04-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20240304_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_robots', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses_meta',
                'ordering': ['pk'],
            },
        ),
        # migrations.AddField(
        #     model_name='course',
        #     name='is_indexable',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AddField(
            model_name='coursemeta',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='courses.Course'),
        ),
    ]
