# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-15 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190720_1417'),
        ('courses', '0006_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='students.Quiz'),
        ),
    ]
