# Generated by Django 2.0.5 on 2024-04-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20240404_1606'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='course',
        #     name='is_indexable',
        #     field=models.BooleanField(default=True),
        # ),
    ]
