# Generated by Django 2.0.5 on 2020-12-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20201201_2302'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursetimelog',
            table='courses_time_logs',
        ),
    ]
