# Generated by Django 2.0.5 on 2024-04-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20240404_1620'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='course',
        #     name='is_indexable',
        # ),
        migrations.AddField(
            model_name='course',
            name='is_noindex',
            field=models.BooleanField(default=False),
        ),
    ]
