# Generated by Django 2.0.5 on 2024-04-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20240404_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeature',
            name='details_long',
            field=models.TextField(blank=True, null=True),
        ),
    ]
