# Generated by Django 2.0.5 on 2020-12-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20201201_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetimelog',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
