# Generated by Django 2.0.5 on 2021-01-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20201201_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.TextField(blank=True, null=True)),
                ('outcomes', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('completion_requirements', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='courses.Course')),
            ],
            options={
                'db_table': 'course_features',
                'ordering': ['pk'],
            },
        ),
    ]
