# Generated by Django 2.0.5 on 2024-04-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_coursefeature_details_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeature',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
