# Generated by Django 2.0.5 on 2024-10-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_coursefeature_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
