# Generated by Django 2.0.5 on 2024-10-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20241025_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogress',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses_progress', to='courses.Enrollments'),
        ),
    ]
