# Generated by Django 2.0.5 on 2024-12-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_courseprogress_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='created_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
