# Generated by Django 2.0.5 on 2021-03-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210225_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='has_progress',
            field=models.BooleanField(default=True),
        ),
    ]
