# Generated by Django 2.0.5 on 2024-12-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_enrollments_created_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollments',
            old_name='created_info',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='enrollments',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
