# Generated by Django 2.0.5 on 2024-12-24 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20241214_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='courses.Enrollments'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluations', to='courses.Course'),
        ),
    ]
