# Generated by Django 2.0.5 on 2021-03-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'CheckIn'), (2, 'CheckOut')], default=1),
        ),
    ]
