# Generated by Django 2.0.5 on 2021-04-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20210417_0236'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='enrollments',
        #     name='course',
        # ),
        # migrations.RemoveField(
        #     model_name='enrollments',
        #     name='user',
        # ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.DeleteModel(
            name='Enrollments',
        ),
    ]
