# Generated by Django 2.0.5 on 2021-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20210419_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
