# Generated by Django 2.0.5 on 2021-09-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_assessrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
    ]
