# Generated by Django 2.0.5 on 2021-09-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20210921_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
