# Generated by Django 2.0.5 on 2021-09-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20210921_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
