# Generated by Django 2.0.5 on 2021-11-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_auto_20210921_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.TextField(default=None, null=True),
        ),
    ]
