# Generated by Django 2.0.5 on 2021-12-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='mark_type',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='coursefeature',
            name='certificate_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursefeature',
            name='duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursefeature',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursefeature',
            name='skill_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='overview',
            field=models.TextField(default=None, null=True),
        ),
    ]
