# Generated by Django 2.0.5 on 2022-02-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20220106_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeature',
            name='credits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
