# Generated by Django 2.0.5 on 2022-04-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_coursefeature_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='meta_description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='meta_tags',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='meta_title',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='page_details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='page_title',
            field=models.TextField(default=None, null=True),
        ),
    ]
