# Generated by Django 2.0.5 on 2022-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_auto_20220429_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='meta_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='meta_tags',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='meta_title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='page_details',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='page_title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
