# Generated by Django 2.0.5 on 2022-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20220429_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='video_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
