# Generated by Django 2.0.5 on 2020-05-19 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0002_auto_20200519_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
