# Generated by Django 2.0.5 on 2020-05-19 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_chat', '0003_auto_20200519_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_members', to='app_chat.Conversation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['conversation'],
            },
        ),
    ]
