# Generated by Django 2.0.5 on 2020-05-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0005_auto_20200524_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
