# Generated by Django 2.0.5 on 2020-06-04 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_chat', '0006_videoroom_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_room_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['room'],
            },
        ),
        migrations.CreateModel(
            name='VideoRoomLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('api_info', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_log_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['room'],
            },
        ),
        migrations.AddField(
            model_name='videoroom',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoroom',
            name='start_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoroomlog',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app_chat.VideoRoom'),
        ),
        migrations.AddField(
            model_name='videoparticipant',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app_chat.VideoRoom'),
        ),
    ]
