# Generated by Django 2.0.5 on 2020-06-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoroom',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
