# Generated by Django 2.0.5 on 2020-06-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0010_participantlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoparticipant',
            name='is_approved',
            field=models.BooleanField(default=0),
        ),
    ]
