# Generated by Django 2.0.5 on 2020-06-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0011_videoparticipant_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_target',
            field=models.CharField(max_length=200),
        ),
    ]
