# Generated by Django 2.0.5 on 2020-06-18 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200519_2230'),
        ('app_chat', '0012_auto_20200614_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_course', to='courses.Course')),
            ],
            options={
                'ordering': ['room'],
            },
        ),
        migrations.RemoveField(
            model_name='videoroom',
            name='course',
        ),
        migrations.AddField(
            model_name='videocourses',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app_chat.VideoRoom'),
        ),
    ]
