# Generated by Django 2.0.5 on 2020-06-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0013_auto_20200619_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoroom',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
