# Generated by Django 2.0.5 on 2021-03-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_content_has_progress'),
        ('app_chat', '0014_auto_20200619_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalVideoRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_video_rooms', to='courses.Course')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
