# Generated by Django 2.0.5 on 2022-01-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0016_remove_conversation_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
    ]
