# Generated by Django 2.0.5 on 2022-07-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_chat', '0018_auto_20220201_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantlog',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participantlog',
            name='room',
        ),
        migrations.RemoveField(
            model_name='videocourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='videocourses',
            name='room',
        ),
        migrations.RemoveField(
            model_name='videoparticipant',
            name='member',
        ),
        migrations.RemoveField(
            model_name='videoparticipant',
            name='room',
        ),
        migrations.RemoveField(
            model_name='videoroom',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='videoroomlog',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='videoroomlog',
            name='room',
        ),
        migrations.DeleteModel(
            name='ParticipantLog',
        ),
        migrations.DeleteModel(
            name='VideoCourses',
        ),
        migrations.DeleteModel(
            name='VideoParticipant',
        ),
        migrations.DeleteModel(
            name='VideoRoom',
        ),
        migrations.DeleteModel(
            name='VideoRoomLog',
        ),
    ]
